# Generated by Django 5.0.7 on 2024-08-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_text', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
